[package]
name = "ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
smart-home = {path="../smart-home"}

[dev-dependencies]
libloading = "0.7.1"
thiserror = "1.0.63"
