[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
smart-home = {path="../smart-home"}
network = {path="../network"}

iced = { git="https://github.com/iced-rs/iced.git", branch = "wgpu-22.0"}
