[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
smart-home = {path = "../smart-home"}
tokio = { version = "1.39.2", features = ["full"] }
